<?
$ct= array(
"Aa Zuidhorn The Netherlands",
"Abandance",
"Abondance",
"Aclens Suisse",
"Agen",
"Aigueblanche",
"Aime La Plgne",
"Aiton",
"Aix Les Bains",
"Alberville",
"Alby Sur Cheran",
"Algajola",
"Allemagne",
"Alleves",
"Allinges",
"Allonzier La Caille",
"Amancy",
"Amberieu",
"Ambes",
"Ambilly",
"Amphion Les Bains",
"Amsterdam Netherlands",
"Ancenis",
"Angers 1",
"Annecy",
"Annecy Le Vieux",
"Annem Asse",
"Annemase",
"Annemasse",
"Annemasse Cadex",
"Annmasse",
"Anthony",
"Antony",
"Aosta Italia",
"Aosta Italie",
"Araches La Frasse",
"Archamps",
"Archamps France",
"Arcueil",
"Arenthon",
"Argenteuil",
"Argonay",
"Arthaz Pont Notre Dame",
"Ashford Kent",
"Asse",
"Athens Greece",
"Aubagne",
"Auffargis",
"Autechaux Roide",
"Avoriaz",
"Ayse",
"Ayze",
"Bagneux",
"Balterswil",
"Bankergcl Sweden",
"Banki Donat U.3.",
"Basildon Uk",
"Bellegarde",
"Bellevaux",
"Belley",
"Benidorm Alicante Espana",
"Benidorm Spain",
"Benidrom Alicante Espagna",
"Berlin",
"Berrechid Maroc",
"Bessancourt",
"Beuvry La Foret",
"Bezons",
"Biard",
"Boege",
"Bogeve",
"Bois Colombes",
"Boissy Sainr Leger",
"Bonchamp Les Laval",
"Bonne",
"Bonneville",
"Bonnville",
"Bons En Chablais",
"Bordeaux",
"Boulogne Billancourt",
"Bourg En Bresse",
"Bourg Saint Maurice",
"Bourg Sant Maurice",
"Bourg St Maurice",
"Brazil",
"Bredaryd Sweden",
"Brenthonne",
"Bresles",
"Brison",
"Brizon",
"Brussel Belgique",
"Brussels Belgium",
"Bruxelles Belgique",
"Burdignin",
"Bussey Saint George",
"Caen",
"Caluire",
"Caluire Et Cuire",
"Canada",
"Cannes",
"Cannes La Bocca",
"Carouge Geneve",
"Carouge Geneve Suisse",
"Carrieres Sur Seine",
"Casablanca Maroc",
"Castres",
"Caussade",
"Cergy Pontoise",
"Cervens",
"Cessy",
"Ch Geneve",
"Ch Geneve 8",
"Ch 1213 Geneve",
"Ch 1215 Geneve 15",
"Ch 125 Geneve 8",
"Ch Geneve",
"Ch Geneve 11",
"Ch Meyrin",
"Ch Meyrin Suisse",
"Ch Plan Les Ouates",
"Chaineux",
"Chalamont",
"Chalandri Greece",
"Chambery",
"Chambray Les Tours",
"Chamomix",
"Chamonix France",
"Chamonix Mt Blanc",
"Champ Sur Marne",
"Champery Suisse",
"Champs Sur Marne",
"Chanaz",
"Charvonnex",
"Chatenay Malabry",
"Chatillon",
"Chatillon Sur",
"Chatou",
"Chaumont En Vexin",
"Chavanod",
"Chaville",
"Chedde Le Fayet",
"Chelles",
"Chemin De Vernes",
"Chene Bourg Suisse",
"Chene Bourgeries",
"Chens Sur Leman",
"Chester Nh 336 Usa",
"Cholet",
"Clermont",
"Cluises",
"Cluises Cedx",
"Cluse",
"Clusee",
"Cluses",
"Codon",
"Cognin",
"Cogolin",
"Cointrin Geneve Suisse",
"Coligny Switzerland",
"Collonges Sous Saleve",
"Cologne",
"Colombes",
"Combloux",
"Comives",
"Contamine",
"Contamine Sur Arve",
"Cordon",
"Cornella De Llobregat",
"Cornwall England",
"Corse",
"Corsier",
"Coulomier",
"Courbevoie",
"Courchevel",
"Courchevel 185",
"Courmayeur",
"Courmayeur Italie",
"Cp Geneve 8",
"Cran Gevrier",
"Cran Montana Swizerland",
"Cran Montna",
"Cranves Sales",
"Creteil",
"Cruseilles",
"Cuzieu",
"Danemark",
"Deutschland Gmbh",
"Divonne Les Bains",
"Dordives",
"Doussard",
"Droue Sur Drouette",
"Dsaint Saens",
"Dublin Ireland",
"Dunkerque",
"Dunstable Beds U.K",
"Dusseldorf Germany",
"Echirole",
"Echirolles",
"Ecully",
"Eger Hongrie",
"Eloise",
"Enghien Les Bains",
"England",
"Enschede The Netherlands",
"Epagny",
"Epone",
"Erkrath Germany",
"Erlangen",
"Esery Reignier",
"Espagne",
"Estonia",
"Eteaux",
"Etrembieres",
"Evian Les Bains",
"Excenevex",
"Farnborough Grande Bretagne",
"Farnham Surrey",
"Fatima",
"Faucigny",
"Faulquemont",
"Ferney Voltaire",
"Fillinges",
"Fitilieu",
"Flaine",
"Flaine Magland",
"Flumet",
"Fraisses",
"Frangy",
"Frankfurt Main Allemagne",
"Frankfurt Main Gremany",
"Froges",
"Gadki Pologne",
"Gaillard",
"Genas",
"Genay",
"Geneva 12 Switzerland",
"Geneva 13 Switzerland",
"Geneva 15 Switzerland",
"Geneva Switzerland",
"Geneve",
"Geneve 11",
"Geneve 11 Suisse",
"Geneve 13 Suisse",
"Geneve 15",
"Geneve 15 Suisse",
"Geneve 26",
"Geneve 3",
"Geneve 3 Ch",
"Geneve 3 Switzerland",
"Geneve 6",
"Geneve 8",
"Geneve 8 Switzerland",
"Geneve Apt",
"Geneve Ch",
"Geneve Suisse",
"Geneve Switzerland",
"Gennevilliers",
"Gex",
"Gex Suisse",
"Gieres",
"Gijon Asturia",
"Gneve Suisse",
"Gouvieux",
"Grand Lancy 1 Ge Svizzera",
"Grande Synthe",
"Granves Sales",
"Gray",
"Grebenhain Germany",
"Grenoble",
"Gressan Ao Italia",
"Gressan Ao Italy",
"Groisy",
"Gstaad Suisse",
"Habere Lullin",
"Habere Poche",
"Halifax",
"Hasselt Belgium",
"Hay Les Roses",
"Herblay",
"High Wycombe United Kingdom",
"Hnagzhou Chine",
"Huelgoat",
"Hungary",
"Hvittingfoss Norway",
"Idaho Usa",
"Ikitelli Istanbul",
"Ireland",
"Issy Les Moulineaux",
"Istanbul Turkey",
"Ivry Sur Seine",
"Jersey",
"Jousered Sweden",
"Jud Bihor Romanie",
"Juvigny",
"Kaliningrad Russia",
"Krakow Pologne",
"La Clusaz",
"La Cote D'Aime",
"La Garenne Colombes",
"La Giettaz",
"La Jubaudiere",
"La Lechere",
"La Motte Servolex",
"La Plagne",
"La Plagne Centre",
"La Plaine St Denis",
"La Roche Sur Foron",
"La Rochelle",
"La Tour",
"Laatzen",
"Laatzen Allemagne",
"Lancrans",
"Landry",
"Lausanne Suisse",
"Le Bouchet",
"Le Fayet",
"Le Fayet France",
"Le Fontanil",
"Le Gets",
"Le Mesnil Le Roi",
"Le Meux",
"Le Pas De L'Echelle",
"Le Plessis Robinson",
"Le Praz De Lys",
"Le Saix",
"Les Angles",
"Les Arcs",
"Les Carroz",
"Les Carroz D'Arraches",
"Les Contamines Montjoie",
"Les Gets",
"Les Houches",
"Les Menuires",
"Les Ulis",
"Lescheraines",
"Levallois",
"Levallois Perret",
"Liege Belgique",
"Limonest",
"Lisboa",
"Lisboa Portugal",
"Locanau",
"Lohr Am Main",
"Lohr Am Main Germany",
"London England",
"London Sw19 7Jt Uk",
"Londres",
"Longstowe",
"Louvain La Neuve Belgique",
"Lpari Park 6",
"Lucinges",
"Lugrin",
"Lyon",
"Lyon 2",
"Lyon 2 Bupo 16544",
"Lyon 2 Cedzx",
"Lyon 7",
"Lyon France",
"Machilly",
"Madrid Espagne",
"Madrid Espana",
"Magland",
"Magland Flaine",
"Magnanville",
"Maison Alfort",
"Maison Laffitte",
"Malakoff",
"Malmo",
"Malmo Sweden",
"Manchester England",
"Marcellaz",
"Marcy L Etoile",
"Marcy L'Etoile",
"Marignier",
"Marignir",
"Marnaz",
"Marne La Vallee 3",
"Maro",
"Marognier",
"Marseille",
"Massy",
"Mecidiyekoy Istanbul Turkey",
"Megeve",
"Megevette",
"Menthon St Bernard",
"Mery",
"Meslin L'Eveque Belgium",
"Messery",
"Metz Tessy",
"Meylan",
"Meyrin Ch",
"Meythet",
"Middlesex Wembley",
"Mieussy",
"Miniac Sous Becherel",
"Miramont De Guyenne",
"Monaco",
"Mont Saxonnex",
"Montaigu",
"Montigny Le Brethonneux",
"Montigny Le Bretonneux",
"Montigny Les Cormeilles",
"Montmeliand",
"Montreal",
"Montreal Canada",
"Montreal Quebec Canada",
"Montreux Suisse",
"Montriond",
"Montrouge",
"Montrouge Juvigny",
"Morance",
"Morillon",
"Morillons",
"Mornex",
"Morzine",
"Morzine Avoriaz",
"Mosco Russia",
"Moscoi",
"Moscou",
"Moscou ",
"Moscou Rusia",
"Moscou Russia",
"Moscou Russie",
"Moscow Russia",
"Moutiers",
"Mullsjo Se 565 28 Sweden",
"Mullsjo Suede",
"Mullsjo Sweden",
"Nangy",
"Nanterre",
"Nantes",
"Neuill Sur Seine",
"Neuilly",
"Neuilly Plaisance",
"Neuilly Sur Seine",
"Neully Sur Seine",
"Nevez",
"New York Us",
"Newcastle Upon Tyne England",
"Newent Gloucestershire",
"Nice",
"Niederwangen",
"Niort",
"Niort 9",
"Nogent Sur Marne",
"Noisy Le Grand",
"Norio Negishi",
"Novalaise",
"Nyon Suisse",
"Oakley Green",
"Odessa Ukraine",
"Onnion",
"Orleans",
"Osterreich",
"Oxfordhire",
"Pakistin",
"Pantin",
"Paris",
"Paris ",
"Paris 12",
"Paris 13",
"Paris 14",
"Paris 16",
"Paris 3Ème Arrondissement",
"Paris 8E Arrondissement",
"Paris France",
"Paris La Defence",
"Paris La Defense",
"Parne Roc",
"Passy",
"Passy Chedde",
"Peeisey Vallandry",
"Peillonnex",
"Peissey Vallandry",
"Perly Suisse",
"Perly Suisse",
"Peronnas",
"Pers Jussy",
"Pers Jusy",
"Persjussy",
"Petit Lancy 1",
"Petit Lancy Suisse",
"Petit Nancy Suisse",
"Piraeus Grece",
"Plagne Centre",
"Plan Les Ouates",
"Plumergat",
"Poissy",
"Poland",
"Pontoise",
"Porto Cervo Italie",
"Portstewart",
"Praz De Lys",
"Praz Sur Arly",
"Prevesin",
"Prevesisin",
"Prevessin",
"Prevessin Moens",
"Pringy",
"Pruszkow Poland",
"Puteaux",
"Quebec Canada",
"Quimper",
"Raanana Israel",
"Rambouillet",
"Rambouillet France",
"Reignier",
"Reignier Esery",
"Rennes",
"Riegnier Esery",
"Rio De Janeiros Brazil",
"Ris Orangis",
"Rockwall Tx",
"Roma Italia",
"Romania",
"Rome Italie",
"Rotennburg",
"Rotkreuz Suisse",
"Rottenburg Neckar",
"Roubais 1",
"Rueil Malmaison",
"Rumilly",
"Rungis",
"Russia",
"Sainr Jeoire En Faucigny",
"Saint Alban Leysse",
"Saint Andre De Boege",
"Saint Avold",
"Saint Cassin",
"Saint Cergues",
"Saint Cloud",
"Saint Cloud France",
"Saint Denis",
"Saint Egreve",
"Saint Etienne De Geoires",
"Saint Etienne De Saint Geoires",
"Saint Etienne De Saint Geoirs",
"Saint Genis Laval",
"Saint Germain D'Esteuil",
"Saint Gervais",
"Saint Gervais Les Bains",
"Saint Herblain",
"Saint Jean D'Aulps",
"Saint Jean De Sixt",
"Saint Jean De Tholome",
"Saint Jeoire",
"Saint Jeoire En Faucigny",
"Saint Joire",
"Saint Jorioz",
"Saint Julien",
"Saint Julien En Genevois",
"Saint Laurent",
"Saint Laurent De Mure",
"Saint Louis",
"Saint Martin De Bellevue",
"Saint Ouen",
"Saint Petersburg",
"Saint Petersburg Russia",
"Saint Pierre En Faucigny",
"Saint Pierre Montlimart",
"Saint Sigismond",
"Saint Tropez",
"Sainte Therese Quebec Canada",
"Saintjeoire En Faucigny",
"Saintpierre En Faucigny",
"Salins Les Thermes",
"Sallanches",
"Salllanches",
"Samoens",
"Sant Andreu De La Barca",
"Sant Jeoire En Faucigny",
"Saran",
"Sarre Union",
"Sassenage",
"Satigny",
"Sauclieres",
"Savigneux",
"Savigny",
"Saxel",
"Scentrier",
"Scientrier",
"Sciez",
"Sciez Sur Leman",
"Scionzier",
"Scoinzier",
"Se 565 28 Mullsjo Sweden",
"Seignosse France",
"Senlis",
"Sequedin",
"Sevres",
"Sevrier",
"Seynod",
"Sfax",
"Siegburg Allemagne",
"Silkeborg Denmark",
"Sillingy",
"Sin Niklass Belgique",
"Sint Niklaas Belgique",
"Sixt Fer A Cheval",
"Sizun",
"Soctvhi Russia",
"Sophia Antipolis",
"Sotchi Russia",
"St Baldoph",
"St Brevin Les Pins",
"St Cergues",
"St Cloud",
"St Etienne De Geoires",
"St Etienne De Geoirs",
"St Germain En Laye",
"St Gervais",
"St Herblain",
"St Jean D'Aulps",
"St Jeoire",
"St Jeoire En Faucigny",
"St Julien En Genevois",
"St Laurent",
"St Laurent De Mure",
"St Marcellin En Forez",
"St Nazaire",
"St Niklaas",
"St Petersbourg",
"St Petersbourg Russia",
"St Petersburg",
"St Petersburg Russia",
"St Petersburg Russie",
"St Pierre En Faucigny",
"St Pierre Montlimart",
"St Sigismond",
"St Tropez",
"Stabekk Norway",
"Staffordshire Gb",
"Stains",
"Statu Mare",
"Ste Therese",
"Stochi Russia",
"Stockholm Sweden",
"Stonetown Zanzibar Tanzania",
"Stuttgart",
"Stuttgart Germany",
"Suce Sur Erdre",
"Suede",
"Suresnes",
"Surrey Royaume Uni",
"Suvay Chatel",
"Sweden",
"Talence",
"Talloires",
"Taninges",
"Taunton Somerset Uk",
"Taurage Lituanie",
"Tel Aviv Iserael",
"Telaviv Israel",
"Thiez",
"Thones",
"Thonex",
"Thonon",
"Thonon Les Bains",
"Thyez",
"Tignes",
"Trappes France",
"Trets",
"Tunis Tunisie",
"Uk",
"Val D'Isere",
"Valancin",
"Valbonne",
"Valencin",
"Vallencin",
"Valmorel",
"Valpeline Aosta",
"Valpelline Aosta",
"Varsovie Pologne",
"Veigy Foncenex",
"Velizy Villacoublay",
"Verbier Suisse",
"Vern Sur Seiche",
"Vernier Suisse",
"Versailles",
"Vesenaz",
"Vesenaz Suisse",
"Vetraz Monthoux",
"Vienna Austria",
"Vigneux De Bretagne",
"Villa La Grand",
"Villad",
"Villar Sur Ollon",
"Villard",
"Villaz",
"Ville En Sallaz",
"Ville La Grand",
"Ville Le Grand",
"Villejuif",
"Villenave D'Ornon",
"Villeneuve Loubet",
"Villeneuve Sur Lot",
"Villeurbanne",
"Viriat",
"Vitry Sur Seine",
"Viuz En Sallaz",
"Viuz La Chieza",
"Voiron",
"Volketswil Suisse",
"Vougy",
"Warszawa Poland",
"Wien",
"Wien Austria",
"Wien Osterreich",
"Wimbledon London",
"Winbledon London",
"Wissous",
"Wreham Wales",
"Wuxi, Jiangsu Province P.R. China",
"Zaventem Belgium",
"Zermatt Suisse");
$i=0;
foreach ($ct as $val) {
	print '"'.$i.'","'.$val.'",
';
	$i++;
}
?>